### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by adjohnson916** [frozzare/json-to-html#4]
Use ESLint for code quality.

**Comment by frozzare** [comment]
I will merge your stuff, but at you can see this is a unmaintained project, the last commit was done i 2013.

**Comment by adjohnson916** [comment]
@frozzare Want to add me as a maintainer, or transfer the repo to me or an org?

**Comment by frozzare** [comment]
@adjohnson916 I can add you as maintainer, but don't do anything crazy 👍

**Comment by adjohnson916** [comment]
@frozzare Thanks, I won't do anything too crazy, and I'll make sure any changes follow semver - I can check with you before some changes if you want.

**Comment by frozzare** [comment]
@adjohnson916 yeah do that.
